### PR TITLE
docs: PanelPlot reference notebook

### PR DESCRIPTION
**Pull request by staceysv**
PanelPlot overview notebook

- [x] basic setup
- [x] PanelPlot component manipulation, zoom, select
- [x] detailed parameter descriptions
- [x] dataset-specific narrative
- [x] polish for images/style/text
- [x] fix gif size

### CODE REVIEW

**Comment by staceysv** [comment]
gonna save a detailed proofreading pass for some point tomorrow/later—otherwise this is kinda reasonable/would love general structural feedback

**Comment by jlzhao27** [comment]
this is great! one nitpick, should we avoid saying `PanelPlot` since that is our internal component name, the UX just shows `Plot` so this should be the docs on how to use `Plot` imo

**Comment by staceysv** [comment]
@jlzhao27 re: PanelPlot—I'm happy to swap the instances of PanelPlot > Plot in this notebook/all reference materials, and I think we really need a term for "plot" that specifically means a "visualization panel in weave" that is distinct from "plot" and "table" and "panel" and unique to Weave so people can anchor on it—that's how I've been using PanelPlot, agreed that's not the ideal term.

**Comment by staceysv** [comment]
- replaced all instances of "PanelPlot" with "Weave Plot" or "plot"—I think this works and our own take on "plot" may still be neat
- text polish pass/proof-read/active voice/condensed some of the prose—ready for review @scottire

**Comment by scottire** [comment]
We should also rename this file. 
I think `Creating_Plots_UI_Guide` makes sense

**Comment by staceysv** [comment]
@scottire feedback addressed!
- renamed notebook
- removed Board link and zoom gif (tried re-recording a few times, still too big....)
- I would say let's merge for now and we can add bar chart/line plot later (and programmatic API if relevant)

**Pull request merged**
