### PR TITLE
chore(weave): Add timestamp to sortable types

### PR DESCRIPTION
**Pull request by jwlee64**
https://wandb.atlassian.net/browse/WB-14680

before
Screenshot 2023-07-31 at 1 54 21 PM

after

weave 1

https://github.com/wandb/weave/assets/25037002/a713172f-d726-4d89-ab47-bcc6b1a764b0

weave0
Screenshot 2023-07-31 at 8 58 37 PM

### CODE REVIEW

**Review by dannygoldstein — APPROVED** [review]
looks good, can you add one more test that tests the non-arrow path (i.e., just sort a straight up list of timestamps) 

this is a really simple test, it doesn't need to use `fake_wandb`

**Comment by jwlee64** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jwlee64** [comment]
recheck

**Comment by jwlee64** [comment]
recheck

**Pull request merged**
