### PR TITLE
feat: Allow for interactive pointSize configuration in pointCloudScene 

### PR DESCRIPTION
**Pull request by jasonkena**
Resolves https://github.com/wandb/wandb/issues/5938
Demo: [Screencast from 2023-07-26 10-24-33.webm](https://github.com/wandb/weave/assets/35003073/8d3f7e29-8e96-4932-b447-57fb8756eb08)

Would appreciate any feedback!

### CODE REVIEW

**Comment by dannygoldstein** [comment]
Hey @jasonkena thanks for the contribution. For some reason our CI checks are not running as they should be on your PR, our devops team is looking into this. 

Code looks good on first glance, our design team is looking at this new pattern.

Will write back with more detailed comments.

**Comment by dannygoldstein** [comment]
cc @davidwallacejackson

**Comment by jlzhao27** [comment]
hey @jasonkena , sorry for the delay, we'll get this reviewed ASAP so we can merge it. We will also need OSS contributors to sign contributor license agreement (cla) which we should have tomorrow. It shouldn't block the review/iteration though.

**Comment by dannygoldstein** [comment]
Hey @jasonkena, still working on our CI but I just tried this on my local machine and it's awesome. Approving provisionally while we figure out how to get CI going, but once that looks good we'll merge this in.

**Comment by jlzhao27** [comment]
hey @jasonkena , thanks for following the bot instructions!  We're still figuring out our cla process, can you share your email where we can send an actual docusign for you? You can share it with jason@ if you don't want to put it publicly.

**Comment by jasonkena** [comment]
@jlzhao27 please send it to the email listed in the patch (https://github.com/wandb/weave/commit/d2e22bc4f8f32e8fbfaa43309efe0e38bf406bce.patch), thanks!

**Review by dannygoldstein — APPROVED** [review]

**Comment by dannygoldstein** [comment]
Thanks for bearing with us as we work out our process, this is our first accepted external contribution.

**Pull request merged**
