### PR TITLE
fix: update prompt to avoid KeyError in running RAG tutorial

### PR DESCRIPTION
**Pull request by xke**
See description and screenshots of issue at https://github.com/wandb/weave/issues/1724

### CODE REVIEW

**Comment by xke** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by scottire — APPROVED** [review]
Thanks for your submission. 
I tried this with GPT-4-turbo and couldn't reproduce after trying a few times. I was able to reproduce a similar error using `gpt-3.5-turbo` and I think your change made it more stable.

**Comment by xke** [comment]
Thanks for the approval, @scottire !
I'm seeing some stuck PR checks, starting with the `Python lint` check with message `Expected — Waiting for status to be reported`.
Have you seen this before? I might need to try more of the suggestions at https://stackoverflow.com/questions/52200096/github-pull-request-waiting-for-status-to-be-reported

**Comment by gtarpenning** [comment]
@xke Hey! As you may have noticed we have been playing with trying to get this in. You may also notice that now more tests have run, nice! However, not all of them. Do you by any chance have a button or clickable link in the "Actions" tab that looks sort of like: "... this is a forked repo, do you want to run actions"? From [this](https://github.com/orgs/community/discussions/50736) github community post. Sorry for the hassle!

**Comment by xke** [comment]
@gtarpenning  Hi! I clicked on the button in the below screen
Screenshot 2024-06-12 at 2 21 48 PM

**Comment by tssweeney** [comment]
I am not sure why CI is clogged here. Applying changes here: https://github.com/wandb/weave/pull/1840

**Comment by tssweeney** [comment]
Thank you for the contribution (: I have applied and merged these changes in https://github.com/wandb/weave/pull/1840.

**Pull request closed without merging**
