### PR TITLE
chore(docs): adding presidio pii cookbook from Hesham

### PR DESCRIPTION
**Pull request by NiWaRe**
In this tutorial, we'll demonstrate how to utilize Weave while preventing your Personally Identifiable Information (PII) data from being incorporated into Weave or the LLMs you employ.

To protect our PII data, we'll employ Microsoft's [Presidio](https://microsoft.github.io/presidio/), a Python-based data protection SDK. This tool provides redaction and replacement functionalities, both of which we will implement in this tutorial.

-- PII tutorial by Hesham

### CODE REVIEW

**Comment by ash0ts** [comment]
Will take a look at this today!

**Review by scottire — CHANGES_REQUESTED** [review]
image
It looks like there needs to be data included for this example to work. Can you make sure this example is runnable by default in Google colab

**Comment by ash0ts** [comment]
Hey! Gonna add some commits here soon to include more generic PII/Data obfuscation tactics

**Comment by ash0ts** [comment]
Hey all, made updates on the #2305 branch. Would love a review

**Comment by jamie-rasmussen** [comment]
Closing in favor of https://github.com/wandb/weave/pull/2305

**Pull request closed without merging**
